### PR TITLE
Fix #65

### LINKED ISSUE #65: CSS is broken on Tablet portrait screen
### Problem
Spacing is not enough between sections.
Data Insight style is broken.

www measurable ai_en-US_(iPad)
www measurable ai_en-US_(iPad) (1)

### PR DESCRIPTION
**Pull request by mailtime-wing**

### CODE REVIEW

**Comment by mailtime-wing** [comment]
@chochihim I am using the implement way you suggest above. 
And i tested with these scenarios 
```
const x = useMedia([1, 2], 3)
x = 1 for mobile
x = 2 for tablet
x = 3 for desktop
```
It also works using the [767, 1023] as mq breakpoints, it will always return the first one`e.g. x = 1` when the screen width satisfies both breakpoints.

**Comment by chochihim** [comment]
@mailtime-wing It looks good. Can you rebase to master to resolve conflict?

**Comment by mailtime-wing** [comment]
@chochihim Resolved all the conflicts.

**Comment by chochihim** [comment]
@mailtime-wing The website crashes now. Can you check carefully?

**Comment by mailtime-wing** [comment]
@chochihim Sorry, it should be ok now.

**Pull request merged**
